### ISSUE TITLE
Peer-to-peer code review 

### ISSUE THREAD

**Issue by shm04** [romans-adi/romans-adi.github.io#10]
https://github.com/romans-adi/romans-adi.github.io/blob/5468d38992a182b7eb57dbd117a8c1dc1b162157/index.html#L139-L143

It would be better that in your error message, you explain why it's not sending the input, something like "email needs to be in lowercase".

https://github.com/romans-adi/romans-adi.github.io/blob/5468d38992a182b7eb57dbd117a8c1dc1b162157/assets/js/app.js#L237-L239

I think you missing the dollar sign "$" at the end of the regex value.

**Comment by romans-adi** [comment]
Thank you very much for your suggestions!

- [x] String closing character added to regex.
- [x] Descriptive message is added to the error message.
